package com.Wsdl2Code.WebServices.WebService1;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 6/26/2014 2:42:04 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.WebService1.WS_Enums.*;
import java.util.List;
import org.ksoap2.SoapEnvelope;
import org.ksoap2.SoapFault;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.HeaderProperty;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import android.os.AsyncTask;
import org.ksoap2.serialization.MarshalFloat;

public class WebService1 {
    
    public String NAMESPACE ="http://tempuri.org/";
    public String url="";
    public int timeOut = 60000;
    public IWsdl2CodeEvents eventHandler;
    public SoapProtocolVersion soapVersion;
    
    public WebService1(){}
    
    public WebService1(IWsdl2CodeEvents eventHandler)
    {
        this.eventHandler = eventHandler;
    }
    public WebService1(IWsdl2CodeEvents eventHandler,String url)
    {
        this.eventHandler = eventHandler;
        this.url = url;
    }
    public WebService1(IWsdl2CodeEvents eventHandler,String url,int timeOutInSeconds)
    {
        this.eventHandler = eventHandler;
        this.url = url;
        this.setTimeOut(timeOutInSeconds);
    }
    public void setTimeOut(int seconds){
        this.timeOut = seconds * 1000;
    }
    public void setUrl(String url){
        this.url = url;
    }
    public void GetDrinksAsync(int id,String naam,String image,String description,int favorite) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        GetDrinksAsync(id, naam, image, description, favorite, null);
    }
    
    public void GetDrinksAsync(final int id,final String naam,final String image,final String description,final int favorite,final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, VectorDrink>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorDrink doInBackground(Void... params) {
                return GetDrinks(id, naam, image, description, favorite, headers);
            }
            @Override
            protected void onPostExecute(VectorDrink result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("GetDrinks", result);
                }
            }
        }.execute();
    }
    
    public VectorDrink GetDrinks(int id,String naam,String image,String description,int favorite){
        return GetDrinks(id, naam, image, description, favorite, null);
    }
    
    public VectorDrink GetDrinks(int id,String naam,String image,String description,int favorite,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("http://tempuri.org/","GetDrinks");
        soapReq.addProperty("id",id);
        soapReq.addProperty("naam",naam);
        soapReq.addProperty("image",image);
        soapReq.addProperty("description",description);
        soapReq.addProperty("favorite",favorite);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("http://tempuri.org/GetDrinks", soapEnvelope,headers);
            }else{
                httpTransport.call("http://tempuri.org/GetDrinks", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorDrink resultVariable = new VectorDrink(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }
    
    public void GetIngredientsAsync(String name) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        GetIngredientsAsync(name, null);
    }
    
    public void GetIngredientsAsync(final String name,final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, VectorIngredient>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorIngredient doInBackground(Void... params) {
                return GetIngredients(name, headers);
            }
            @Override
            protected void onPostExecute(VectorIngredient result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("GetIngredients", result);
                }
            }
        }.execute();
    }
    
    public VectorIngredient GetIngredients(String name){
        return GetIngredients(name, null);
    }
    
    public VectorIngredient GetIngredients(String name,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("http://tempuri.org/","GetIngredients");
        soapReq.addProperty("name",name);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("http://tempuri.org/GetIngredients", soapEnvelope,headers);
            }else{
                httpTransport.call("http://tempuri.org/GetIngredients", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorIngredient resultVariable = new VectorIngredient(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }
    
    public void FindMixesAsync(VectorString ingredienten) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        FindMixesAsync(ingredienten, null);
    }
    
    public void FindMixesAsync(final VectorString ingredienten,final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, VectorMix>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorMix doInBackground(Void... params) {
                return FindMixes(ingredienten, headers);
            }
            @Override
            protected void onPostExecute(VectorMix result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("FindMixes", result);
                }
            }
        }.execute();
    }
    
    public VectorMix FindMixes(VectorString ingredienten){
        return FindMixes(ingredienten, null);
    }
    
    public VectorMix FindMixes(VectorString ingredienten,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("http://tempuri.org/","FindMixes");
        soapReq.addProperty("ingredienten",ingredienten);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("http://tempuri.org/FindMixes", soapEnvelope,headers);
            }else{
                httpTransport.call("http://tempuri.org/FindMixes", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorMix resultVariable = new VectorMix(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }
    
    public void GetMixesAsync(int id,String naam) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        GetMixesAsync(id, naam, null);
    }
    
    public void GetMixesAsync(final int id,final String naam,final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, VectorMix>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorMix doInBackground(Void... params) {
                return GetMixes(id, naam, headers);
            }
            @Override
            protected void onPostExecute(VectorMix result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("GetMixes", result);
                }
            }
        }.execute();
    }
    
    public VectorMix GetMixes(int id,String naam){
        return GetMixes(id, naam, null);
    }
    
    public VectorMix GetMixes(int id,String naam,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("http://tempuri.org/","GetMixes");
        soapReq.addProperty("id",id);
        soapReq.addProperty("naam",naam);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("http://tempuri.org/GetMixes", soapEnvelope,headers);
            }else{
                httpTransport.call("http://tempuri.org/GetMixes", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorMix resultVariable = new VectorMix(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }
    
    public void GetMixIngredientsAsync(String drinknaam) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        GetMixIngredientsAsync(drinknaam, null);
    }
    
    public void GetMixIngredientsAsync(final String drinknaam,final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, VectorIngredient>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorIngredient doInBackground(Void... params) {
                return GetMixIngredients(drinknaam, headers);
            }
            @Override
            protected void onPostExecute(VectorIngredient result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("GetMixIngredients", result);
                }
            }
        }.execute();
    }
    
    public VectorIngredient GetMixIngredients(String drinknaam){
        return GetMixIngredients(drinknaam, null);
    }
    
    public VectorIngredient GetMixIngredients(String drinknaam,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("http://tempuri.org/","GetMixIngredients");
        soapReq.addProperty("drinknaam",drinknaam);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("http://tempuri.org/GetMixIngredients", soapEnvelope,headers);
            }else{
                httpTransport.call("http://tempuri.org/GetMixIngredients", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorIngredient resultVariable = new VectorIngredient(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }
    
}
